- name: Pull Log Image
  docker_image:
    name: "{{ LOG_IMAGE_NAME }}"

- name: Run Log Server
  docker_container:
    name: "{{ LOG_SERVER_NAME }}"
    image: "{{ LOG_IMAGE_NAME }}"
    networks:
      - name: "{{ NET }}"
    ports:
      - "12201:12201/udp"
    command: ./bin/logstash -e "input { gelf { type => docker } } output { elasticsearch { hosts => [\"agr.{{ NET }}.elasticsearch.server\"] } stdout { } }"
